### ISSUE TITLE
NetSwitch: Separate button

### ISSUE THREAD

**Issue by sebus1201** [tantecky/android#1]
Hello
Thank You for the great app. I've been waiting for this app many years.
I have one request. It is possible that button for mobile data and wifi will be separate.
Thanks in advance.

**Comment by tantecky** [comment]
Hi, 
it is definitely doable. I'll give it a try.
Thank you for your feedback.

**Comment by tantecky** [comment]
I've published version 1.1, which address this issue. So it should be on F-droid in several days.

**Comment by sebus1201** [comment]
Thank You.
Works perfectly.
Best wishes.
