### ISSUE TITLE
NetSwitch: Mobile data switch only on rooted phones

### ISSUE THREAD

**Issue by RufioHugo** [tantecky/android#2]
A long awaited very small widget, faster than any menu - thank you!

But;
- on a normal phone the mobile data switch displays "red/disconnected" all the time
- on a normal phone the mobile data switch doesn't work because "lack of root rights"

On a rooted phone the mobile data switch displays the state at the time the widget was installed and only works and changes the icon when given root access.

Could it be modified into a widget working without root?

**Comment by tantecky** [comment]
Hi,
Thank you for your feedback. 
Since Android 5 ordinary apps are no longer allowed to control mobile data (due to security reasons). So root access is required to bypass this limitation :(

**Comment by RufioHugo** [comment]
Thanks for your quick reply - but my question was very unclear ... sorry on that!

I understood that toggling mobile data needs root access (it's in the description at f-droid also, I read that stuff. ;->)!

Meant was;
Is there a way to change the icon without root access?
Because it otherwise displays half the time the false state ...

If not - separated buttons will be an advantage because of the quick way switching WiFi without beeing irritated by a false mobile data icon.

Greetings!

**Comment by tantecky** [comment]
Hi,
Yes, you are correct. The separate widgets is the way to go. Actually I have already implemented this functionality at the new version 1.1 as you can see [here](https://github.com/tantecky/android/tree/master/NetSwitch). Now it is on F-droid to catch up with the update :)

**Comment by RufioHugo** [comment]
Thx!
