### ISSUE TITLE
NetSwitch: Widget crashes while trying to use data switch

### ISSUE THREAD

**Issue by mcyusuf** [tantecky/android#3]
#### Expected behavior
The widget works to switch data and WiFi on and off, the WiFi switch works well, but the data switch which requires root access should also work when root access has been provided.

#### Actual behavior
After giving root access to the widget, the data switch crashes the widget once clicked, thus leaving the widget unresponsive to further use.

#### How to reproduce
Download Netswitch app from fdroid store.<br>
On the launcher homescreen, navigate to widgets.<br>
Select Netswitch and add to homepage.<br>
Grant root access.<br>
Click the data switch button.<br>
Widget crashes and stays unresponsive.

* Widget: Netswitch (latest version on fdroid)
* Operating system: Android 5.1 Lollipop tablet
* Root access: Kingroot

#### Recording Of The Bug
![videotogif_2018.02.08_23.00.54.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518162609/gyj1ilydkpn0wrrpqauj.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mcyusuf/widget-crashes-while-trying-to-use-data-switch">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dimqua** [comment]
I have the same problem too. LineageOS 14.1.

**Comment by tantecky** [comment]
Hi guys,
Thank you for your feedback. Could you provide me a [Logcat output](https://forum.xda-developers.com/showthread.php?t=1726238) after the crash so I can track down this issue.
I have LOS 14.1 as well and mobile data togging is working for me :)

**Comment by mcyusuf** [comment]
Would do so soon

**Comment by mcyusuf** [comment]
Would do so soon

**Comment by mcyusuf** [comment]
[widget.txt](https://github.com/tantecky/android/files/1732369/widget.txt)
[widget2.txt](https://github.com/tantecky/android/files/1732370/widget2.txt)

**Comment by tantecky** [comment]
Thank you! I'll take a look.

**Comment by tantecky** [comment]
So, I have tried to fixed it.
Could you try it and provide me a logcat output again?
- Uninstall NetSwitch
- Download [app-debug.zip](https://github.com/tantecky/android/files/1733793/app-debug.zip)
- Rename `app-debug.zip` to `app-debug.apk`
- Install and try it

Thank you!

**Comment by mcyusuf** [comment]
Its no more crashing. Yet could switch WiFi on and off on my device. 
But data gets switched on. But not off. 
Am using dual SIM phones. 
Logcat below.

**Comment by mcyusuf** [comment]
[2018-02-17-19-14-53.txt](https://github.com/tantecky/android/files/1733970/2018-02-17-19-14-53.txt)

**Comment by tantecky** [comment]
Good point. I haven't tested the widget on dual SIM phones (because I do not have any).
- Are you able to enable data per SIM, or is there only one global switch?
- When you clicked on the widget, did it enable mobile data on both SIMs?
- Before clicking on the widget, had you disabled data on both SIMs?

**Comment by mcyusuf** [comment]
* I can enable for Sims differently. By selecting the preferred SIM from a pop-up. Thus making it default data SIM. With that the switch would on and off data on it. 
* It enabled my just one SIM that was formerly selected as default data SIM.
* I can't disable both SIM. One has to be default data SIM. I had SIM 1 on default. Switched of f data. And the widget could on it. But couldn't off it back. 

Thanks.

**Comment by tantecky** [comment]
Ok, thanks for the clarification.
Here is my second attempt: [app-debug.zip](https://github.com/tantecky/android/files/1735008/app-debug.zip)
I have modified an method for toggling mobile data. It is slightly different approach and for my 1 SIM phone it is working. 
I am looking forward to your feedback.

**Comment by tantecky** [comment]
Hi,
Have you managed to test it? 
Thank you!

**Comment by tantecky** [comment]
The version 1.2 implements fixes mentioned above, so I hope it helps.
