### ISSUE TITLE
NetSwitch: Logo contribution

### ISSUE THREAD

**Issue by revilationer** [tantecky/android#4]
Hi PO!
I've designed a new logo for your app.
I hope you like it. Free to use at all for you, you can find .ai - .png - .pdf versions at link.
https://utopian.io/utopian-io/@revilationer/my-logo-for-netswitch

**Comment by tantecky** [comment]
Hi,
Thank you for your contribution. 
These days it is much better to provide a logo for an Android app as 2 separated SVG files (background and foreground). Take a look at [here](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html) and [here](https://medium.com/@ianhlake/vectordrawable-adaptive-icons-3fed3d3205b5).
Moreover do you think that widget buttons should be changed as well to be in visual sync whit your logo?
Thank you

**Comment by revilationer** [comment]
I will upload SVG files ASAP.
If you want to change widget buttons too, you can write task request on UTOPIAN, then i would make widget versions.
It is free for you :)

**Comment by dimqua** [comment]
> to change widget buttons too, you can write task request on UTOPIAN, then i would make widget versions.

@tantecky @revilationer please do it.

**Comment by tantecky** [comment]
@dimqua I am thinking about it. Do you have any experience with Utopinan? May be you can create a request as well?

**Comment by revilationer** [comment]
@tantecky i can help you over here, too. What kind of thing do you want as a widget?

**Comment by tantecky** [comment]
Besides the app logo the widget consists of 2 buttons. For toggling WiFi and mobile data. Each one has enabled/disabled state as well. See  [screenshots](https://github.com/tantecky/android/tree/master/NetSwitch) on the main page. 
Thank you!

**Comment by revilationer** [comment]
Will you change the icon to that i have made? I can design the widget icons as the same template?

**Comment by tantecky** [comment]
If you provide the widget icons as well, I do not have problem with it :)
I just want icons to be consistent. The logo shouldn't look different then other icons.
Finally for easier use in Android please provide svg files as well.
Thank you.

**Comment by revilationer** [comment]
Hey @tantecky, all is done.
![aaa](https://user-images.githubusercontent.com/35149966/37867693-2724ca3c-2fad-11e8-849d-b8d97ba5f7f5.gif)
You can find out widget's project files from [here](https://drive.google.com/drive/folders/1Lsb-yvcPD8507wR4we-xiqg9AEGLsX3O)
I've uploaded logo.svg file for you to source files, you can find out it from [here](https://drive.google.com/drive/folders/1WiT7MZqVXyO40RyWbntP74MpIcEGCGW9)
I'm waiting for your throughts :)

**Comment by revilationer** [comment]
![widget](https://user-images.githubusercontent.com/35149966/37872122-97abc682-3009-11e8-8ec5-a9d93c5edce5.gif)
What about now ?

**Comment by tantecky** [comment]
That's more like it! Now I will prepare it for the app and post it here for your review. It will take some time so please be patient :)

**Comment by revilationer** [comment]
OK! How long time take this process? I need it merged to post my contribution on utopian

**Comment by tantecky** [comment]
I see. I think it will take several days to test it/process it.

**Comment by revilationer** [comment]
Ok, good luck :)

**Comment by tantecky** [comment]
So here is my attempt:
![preview](https://user-images.githubusercontent.com/11583425/37873159-b37d838e-3016-11e8-94dd-6d7fa1d715e5.png)

Tell me what do you think.

**Comment by revilationer** [comment]
Umm, why you dont want to use mine?
I think these are not eye catching and the colors are awful

**Comment by tantecky** [comment]
But these are your icons. I just modified colors.
Anyway [here](https://transfer.sh/V9fev/preview.svg) is a svg file, so please modify it to make it eye catching.
I am look forward to your feedback.

**Comment by revilationer** [comment]
Sir, i mean the graphics that you made more complicated than mines. I wanted to make a design simple without contours etc. But if you didnt like i can change the colors. Do you have discord account? We can chat rapidly overthere

**Comment by tantecky** [comment]
You can join here: https://discord.gg/PY9B3

**Comment by revilationer** [comment]
@tantecky I am waiting for your throughts, can you check discord channel?

**Comment by tantecky** [comment]
Looks great. Is the background color the same as [here](https://drive.google.com/drive/folders/1Lsb-yvcPD8507wR4we-xiqg9AEGLsX3O)? Can you provide a svg file of the logo? Sorry for waiting for my feedback, but I am not using Discord.

**Comment by revilationer** [comment]
Hi,
You can find out the svg file of logo here (logo1.svg left top corner): https://drive.google.com/drive/folders/1GPa4NEE2H2HoCGw54HXA7DEeTY-MHjGS
Also, as flat icon version: https://drive.google.com/drive/folders/172yJ9--clSuGA0GpM0Vy_GM4nDhbAqNs
As logomark version: https://drive.google.com/drive/folders/1hbRkkujUkVnwdfNMsWBQr53EVXR9EyKd

**Comment by tantecky** [comment]
I've just updated [screenshots](https://github.com/tantecky/android/tree/master/NetSwitch/metadata/en-US/images) and [widget previews](https://github.com/tantecky/android/tree/master/NetSwitch/app/src/main/res/drawable-nodpi). I am still testing the app before a new release, but it looks promising.

**Comment by revilationer** [comment]
I'm glad to hear that. May be the logo could look better without shadow

**Comment by tantecky** [comment]
Well I've not done that. This how Android studio generated it. I guess it is because Google is pushing Material design look on Android and on the other hand Flat design is more like an Apple thing.

**Comment by tantecky** [comment]
So version 1.3 with your graphics is out. It usually takes several days for F-Droid pick up changes and build a new version. Nevertheless, thank you for your contribution :smirk:

**Comment by tantecky** [comment]
[Published](https://f-droid.org/en/packages/cz.antecky.netswitch/)
