### ISSUE TITLE
NetSwitch: LineageOS 16 -> 17

### ISSUE THREAD

**Issue by andreabenetton** [tantecky/android#5]
As LineageOS dropped the support of su to root the device in the upgrade to 17.1, it can happen that if you give netswitch root access to manage mobile data, after the upgrade, the mobile data is turned off and there is no way to turn it on again. I have solved by reinstalling but a notice for other users when installing the app could be helpful.

**Comment by tantecky** [comment]
Hi,
Thank you for your feedback, Unfortunately I am no longer using LineageOS. However root  access still might be gain via [Magisk](https://github.com/topjohnwu/Magisk) tool set, but I have not tried it by myself.
